import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Wallet from '../components/wallet'
import Footer from '../components/footer'
import LogoutHomePage from '../components/loggedOutHomePage'
import LoginHomePage from '../components/loggedInHomePage'
import { useWeb3React } from '@web3-react/core'
export default function Home() {
  const {active} = useWeb3React()
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wallet/>
      <main className={styles.main}>
        <Image
          src='/wizard.png'
          alt="Picture of the author"
          width={200}
          height={200}
        />
        <h1 className={styles.title}>
          Welcome to  <a href="./">Web3</a> 
        </h1>
      {active?<LoginHomePage/>:<LogoutHomePage/>}
      </main>
      <Footer/>
    </div>
  )
}
