import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Wallet from '../components/wallet'
import Footer from '../components/footer'
import LogoutHomePage from '../components/logoutHomePage'
import LoginHomePage from '../components/loginHomePage'
import { useWeb3React } from '@web3-react/core'
export default function Home() {
  const {active} = useWeb3React()
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wallet/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="./">Web3</a>
        </h1>
      {active?<LoginHomePage/>:<LogoutHomePage/>}
      </main>
      <Footer/>
    </div>
  )
}
